version: '3'

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3306:3306
  adminer:
    image: adminer
    ports:
    - 8080:8080
  redis:
    image: redis
    ports:
      - 6369:6379
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306